# Generated by Django 5.2 on 2026-04-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_rename_person_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='books',
            name='last_name',
        ),
        migrations.AddField(
            model_name='books',
            name='book_author',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='book_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
