# Generated by Django 5.2 on 2026-04-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_remove_books_first_name_remove_books_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='amount_of_copies',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
