# Generated by Django 5.2.11 on 2026-04-20 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_customer_remove_books_id_books_book_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.books')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.customer')),
            ],
        ),
    ]
