# Generated by Django 5.2.11 on 2026-04-21 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0008_bookreturn_issuedbooks_delete_bookregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('date_issued', models.DateField()),
                ('return_by_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.books')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.customer')),
            ],
        ),
    ]
