# Generated by Django 5.2.11 on 2026-04-21 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0009_bookregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreturn',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookreturn',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='issuedbooks',
            name='book',
        ),
        migrations.RemoveField(
            model_name='issuedbooks',
            name='customer',
        ),
        migrations.CreateModel(
            name='BookTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('registered', 'Registered/Available'), ('issued', 'Issued'), ('returned', 'Returned')], default='registered', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.books')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='BookRegistration',
        ),
        migrations.DeleteModel(
            name='BookReturn',
        ),
        migrations.DeleteModel(
            name='IssuedBooks',
        ),
    ]
