# Generated by Django 5.2.11 on 2026-04-23 08:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0010_remove_bookreturn_book_remove_bookreturn_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.AlterModelOptions(
            name='booktransaction',
            options={'ordering': ['-issue_date']},
        ),
        migrations.RemoveField(
            model_name='booktransaction',
            name='status',
        ),
        migrations.AddField(
            model_name='booktransaction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booktransaction',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booktransaction',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BookReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('book_condition', models.CharField(choices=[('Good', 'Good'), ('Minor Damage', 'Minor Damage'), ('Major Damage', 'Major Damage'), ('Lost', 'Lost')], default='Good', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_record', to='libraryapp.booktransaction')),
            ],
            options={
                'ordering': ['-returned_at'],
            },
        ),
    ]
