# Generated by Django 5.2 on 2026-04-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0011_rename_books_book_alter_booktransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktransaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='booktransaction',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='booktransaction',
            name='is_returned',
        ),
        migrations.RemoveField(
            model_name='booktransaction',
            name='issued_by',
        ),
        migrations.AddField(
            model_name='booktransaction',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered/Available'), ('issued', 'Issued'), ('returned', 'Returned')], default='registered', max_length=20),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BookReturn',
        ),
    ]
