# Generated by Django 5.2.11 on 2026-04-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0013_bookreturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreturn',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='bookreturn',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
