# Generated by Django 5.2.11 on 2026-04-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0014_remove_bookreturn_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amount_of_copies',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
