# Generated by Django 5.2.11 on 2026-04-29 05:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0015_alter_book_amount_of_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreturn',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookreturn',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
