# Generated by Django 5.2.11 on 2026-04-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0016_bookreturn_is_late_bookreturn_late_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktransaction',
            name='status',
        ),
    ]
