# Generated by Django 5.2 on 2026-07-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0018_alter_book_book_author_alter_book_book_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
